language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "8"
  - "9"
before_script:
  - tmp=$(mktemp --directory)
  - bash -O dotglob -O extglob -c 'mv !(node_modules|test) "$1"/' bash "$tmp"
  - pack=$(npm pack "$tmp")
  - tar --strip-components=1 -x -v -f "$pack"
script:
  - node test
